spring:
  datasource:
    url: jdbc:mysql://121.14.240.149:3306/newmt?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: linbin_43KDa
    password: tKkO_7xsqB87LaH7
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  type-aliases-package: com.model

eureka:
  client:
    serviceUrl:
      defaultZone: http://centertest.39.net:8084/eureka

# 设置熔断超时时间
#  hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=10000
  # 关闭Hystrix功能（不要和上面的配置一起使用）
#  feign.hystrix.enabled=false
  # 关闭熔断功能
#  hystrix.command.default.execution.timeout.enabled=false

feign:
  hystrix:
    enabled: true
