server:
    port: 8082

spring:
  application:
    name: mix-service
  datasource:
    url: jdbc:mysql://172.16.3.121:3306/mix?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: mix_lan
    password: eyZ/r2vd8Pbl
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  type-aliases-package: com.model

eureka:
  client:
    serviceUrl:
      defaultZone: http://mac.39.net:8084/eureka

feign:
  hystrix:
    enabled: true